name: Go Proxy Scanning

on:
  # Bisa dijalankan manual dan otomatis tiap 6 jam
  workflow_dispatch:
  

jobs:
  update-proxies:
    runs-on: ubuntu-latest
    name: Scan Proxy

    steps:
    - name: ğŸ“‚ Checkout Repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GIT_TOKEN }}

    - name: ğŸ’¾ Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22' # atau versi Go yang Kak Yumi pakai

    - name: ğŸ“¦ Install Go Dependencies
      run: |
        go mod tidy

    - name: â–¶ï¸ Run Go Proxy Scan
      run: |
        go run ./SC-Emilia/main.go

    - name: ğŸ“¤ Commit and Push Changes
      if: ${{ success() }}
      run: |
        git config --global user.name "Github Actions"
        git config --global user.email "actions@github.com"
        git add .
        git commit -m "ğŸ” Update proxyip"
        git push origin main --force
